# Generated by Django 4.0.4 on 2022-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('createa_data', models.DateField(auto_now_add=True)),
                ('updeted_data', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
