# Generated by Django 4.0.4 on 2022-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
