# Generated by Django 4.0.4 on 2022-04-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookdetails_bookcomet'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gengre',
            field=models.CharField(choices=[('ROMACE', 'romace'), ('ADVENTURES', 'priklyucheniya'), ('HAREM', 'harem'), ('ANIME', 'anime')], max_length=90, null=True),
        ),
    ]
