# Generated by Django 4.0.4 on 2022-04-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_gengre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gengre',
            field=models.CharField(choices=[('ROMACE', 'romace'), ('ADVENTURES', 'priklyucheniya'), ('ANIME', 'anime')], max_length=90, null=True),
        ),
    ]
